FaceManga\MainBundle\Entity\Anime:
    type: entity
    repositoryClass: FaceManga\MainBundle\Entity\AnimeRepository
    table: anime
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    gedmo:
        loggable: true
    fields:
        name:
            type: string
            length: 255
            gedmo:
                - versioned
        year:
            type: integer
            gedmo:
                - versioned
        episodes:
            type: integer
            gedmo:
                - versioned
        genre:
            type: array
            gedmo:
                - versioned
        description:
            type: text
            gedmo:
                - versioned
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                      - name
    indexes:
        search_idx:
            columns: slug
    manyToMany:
        likes:
            targetEntity: User
            inversedBy: likes
            joinTable:
                name: animes_likes
                joinColumns:
                    user_id:
                        referencedColumnId: id
                inverseJoinColumns:
                    anime_id:
                        referencedColumnId: id
    lifecycleCallbacks: {  }
