FaceManga\MainBundle\Entity\Anime:
    type: entity
    repositoryClass: FaceManga\MainBundle\Entity\AnimeRepository
    table: anime
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        year:
            type: integer
        episodes:
            type: integer
        genre:
            type: array
        description:
            type: text
        view_count:
            type: integer
    manyToMany:
        likes:
            targetEntity: User
            inversedBy: likes
            joinTable:
                name: animes_likes
                joinColumns:
                    user_id:
                        referencedColumnId: id
                inverseJoinColumns:
                    anime_id:
                        referencedColumnId: id
    lifecycleCallbacks: {  }
