FaceManga\MainBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        likes:
            targetEntity: Anime
            mappedBy: likes