facemanga_main_dashboard:
    pattern:  /
    defaults: { _controller: FaceMangaMainBundle:Dashboard:index }
    
facemanga_main_anime_create:
    pattern: /create
    defaults: { _controller: FaceMangaMainBundle:Anime:create }
    
facemanga_main_anime_show:
    pattern: /anime/{slug}
    defaults: { _controller: FaceMangaMainBundle:Anime:show }
    
facemanga_main_anime_edit:
    pattern: /edit/{slug}
    defaults: { _controller: FaceMangaMainBundle:Anime:edit }
    
facemanga_main_anime_delete:
    pattern: /delete/{id}
    defaults: { _controller: FaceMangaMainBundle:Anime:delete }

facemanga_main_ajax_anime:
    pattern: /ajax/anime
    defaults: { _controller: FaceMangaMainBundle:Ajax:anime }

facemanga_main_ajax_switchlike:
    pattern: /ajax/switchlike
    defaults: { _controller: FaceMangaMainBundle:Ajax:switchLike }
facemanga_main_admin_index:
    pattern: /admin
    defaults: { _controller: FaceMangaMainBundle:Admin:index }

facemanga_main_admin_console:
    pattern: /admin/console
    defaults: { _controller: FaceMangaMainBundle:Admin:console }
