facemanga_main_dashboard:
    pattern:  /
    defaults: { _controller: FaceMangaMainBundle:Dashboard:index }
    
facemanga_main_anime_create:
    pattern: /create
    defaults: { _controller: FaceMangaMainBundle:Anime:create }
    
facemanga_main_anime_show:
    pattern: /anime/{id}
    defaults: { _controller: FaceMangaMainBundle:Anime:show }
    
facemanga_main_anime_delete:
    pattern: /delete/{id}
    defaults: { _controller: FaceMangaMainBundle:Anime:delete }
