parameters:
#    face_manga_main.example.class: FaceManga\MainBundle\Example

services:
    facemanga_main.menu_builder:
        class: FaceManga\MainBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        
    facemanga.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: facemanga_main.menu_builder
        factory_method: createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }

    twig.extension.pcre:
        class: Jasny\Twig\PcreExtension
        tags:
          - { name: twig.extension }