parameters:
#    face_manga_main.example.class: FaceManga\MainBundle\Example

services:
#    face_manga_main.example:
#        class: %face_manga_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
