FaceManga\MainBundle\Entity\Anime:
    properties:
        year:
            - Range:
                min: 1
                max: 2014
                minMessage: Das Jahr muss mindestens 1 sein.
                maxMessage: Das Jahr ist ungültig.
                invalidMessage: Das Jahr muss eine Zahl sein.
        episodes:
            - Type:
                type: integer
                message: Muss eine Zahl sein.
            - GreaterThanOrEqual:
                value: 0
                message: Muss groesser oder gleich 0 sein.